const browserGlobals = {
  window: 'readonly',
  document: 'readonly',
  localStorage: 'readonly',
  sessionStorage: 'readonly',
  navigator: 'readonly',
  AudioContext: 'readonly',
  webkitAudioContext: 'readonly',
  requestAnimationFrame: 'readonly',
  FileReader: 'readonly',
  setInterval: 'readonly',
  clearInterval: 'readonly',
  setTimeout: 'readonly',
  clearTimeout: 'readonly',
  alert: 'readonly',
  prompt: 'readonly',
  confirm: 'readonly',
  console: 'readonly',
  JSON: 'readonly',
  Math: 'readonly',
  Date: 'readonly',
  Object: 'readonly',
  Array: 'readonly',
  parseInt: 'readonly',
  parseFloat: 'readonly',
  isNaN: 'readonly',
  encodeURI: 'readonly',
  decodeURI: 'readonly',
  location: 'readonly',
  history: 'readonly',
  screen: 'readonly',
  Image: 'readonly',
  Blob: 'readonly',
  URL: 'readonly',
  Response: 'readonly',
  Promise: 'readonly',
  Symbol: 'readonly',
  Map: 'readonly',
  Set: 'readonly',
  WeakMap: 'readonly',
  WeakSet: 'readonly',
  Proxy: 'readonly',
  Reflect: 'readonly',
  Intl: 'readonly',
};

export default [
  {
    files: ['assets/**/*.js'],
    languageOptions: {
      ecmaVersion: 'latest',
      sourceType: 'script',
      globals: browserGlobals,
    },
    rules: {
      'no-unused-vars': ['warn', { argsIgnorePattern: '^_' }],
      'no-undef': 'warn',
      'prefer-const': 'warn',
      'no-var': 'warn',
      'no-console': 'off',
      semi: ['warn', 'always'],
      quotes: ['warn', 'single'],
      indent: ['warn', 2],
      'no-mixed-spaces-and-tabs': 'error',
      'no-trailing-spaces': 'warn',
      'eol-last': 'warn',
      'comma-dangle': ['warn', 'always-multiline'],
      'no-empty': 'warn',
      'no-extra-semi': 'warn',
    },
  },
  {
    ignores: ['node_modules/**', 'dist/**'],
  },
];
