export default {
  env: {
    browser: true,
    es2022: true,
  },
  extends: ['eslint:recommended'],
  parserOptions: {
    ecmaVersion: 'latest',
    sourceType: 'script',
  },
  rules: {
    'no-unused-vars': ['error', { argsIgnorePattern: '^_' }],
    'no-undef': 'error',
    'prefer-const': 'warn',
    'no-var': 'error',
    'no-console': 'off',
    'semi': ['error', 'always'],
    'quotes': ['warn', 'single'],
    'indent': ['warn', 2],
    'no-mixed-spaces-and-tabs': 'error',
    'no-trailing-spaces': 'warn',
    'eol-last': 'warn',
    'comma-dangle': ['warn', 'always-multiline'],
    'no-empty': 'warn',
    'no-extra-semi': 'warn',
  },
  globals: {
    window: 'readonly',
    document: 'readonly',
    localStorage: 'readonly',
    sessionStorage: 'readonly',
    navigator: 'readonly',
    AudioContext: 'readonly',
    webkitAudioContext: 'readonly',
    requestAnimationFrame: 'readonly',
    FileReader: 'readonly',
    setInterval: 'readonly',
    clearInterval: 'readonly',
    setTimeout: 'readonly',
    clearTimeout: 'readonly',
    alert: 'readonly',
    prompt: 'readonly',
    confirm: 'readonly',
    console: 'readonly',
    JSON: 'readonly',
    Math: 'readonly',
    Date: 'readonly',
    Object: 'readonly',
    Array: 'readonly',
    parseInt: 'readonly',
    parseFloat: 'readonly',
    isNaN: 'readonly',
    encodeURI: 'readonly',
    decodeURI: 'readonly',
    location: 'readonly',
    history: 'readonly',
    screen: 'readonly',
    Image: 'readonly',
    Blob: 'readonly',
    URL: 'readonly',
    Response: 'readonly',
    Promise: 'readonly',
    Symbol: 'readonly',
    Map: 'readonly',
    Set: 'readonly',
    WeakMap: 'readonly',
    WeakSet: 'readonly',
    Proxy: 'readonly',
    Reflect: 'readonly',
    Intl: 'readonly',
  },
  ignorePatterns: ['node_modules/', 'dist/'],
};
